version: '3.7'
services:
  # Apache
  www:
    image: manchenkoff/resty
    ports:
      - 80:80
      - 443:443
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - ./:/var/www

  # MySQL
  db:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
    volumes:
      - ./runtime/database:/var/lib/mysql