#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

define('YII_DEBUG', false);
define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/app/config/console.php';

$application = new yii\console\Application($config);

// remove unnecessary controllers
foreach (['asset', 'cache', 'fixture', 'message', 'serve'] as $controller) {
    unset($application->controllerMap[$controller]);
}

$exitCode = $application->run();
exit($exitCode);